/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgFestival;

import pkgVues.jpAjoutTChambre;
import org.hibernate.Session;
import pkgEntite.HibernateUtil;
import pkgVues.jpAjoutEtab;
import pkgVues.jpAjoutOffre;
import pkgVues.jpConsulterEtab;
import pkgVues.jpConsulterOffre;
import pkgVues.jpConsulterChambre;


/**
 *
 * @author etudsio
 */
public class jfrMenu extends javax.swing.JFrame {
    private static Session session = HibernateUtil.getSessionFactory().openSession();
    protected jpAjoutEtab jpAjoutEtab = new jpAjoutEtab();
    protected jpConsulterEtab jpConsulterEtab = new jpConsulterEtab();
    protected jpAjoutTChambre jfAjoutTChambre = new jpAjoutTChambre();
    protected jpConsulterOffre jpConsulterOffre = new jpConsulterOffre();
    protected jpAjoutOffre jpAjoutOffre = new jpAjoutOffre();
    protected jpConsulterChambre jpListeChambre = new jpConsulterChambre();

    /**
     * Creates new form jfrMenu
     */
    public jfrMenu() {
        initComponents();
    }    

    public static Session getSession() {
        return session;
    }

    public static void setSession(Session session) {
        jfrMenu.session = session;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu = new javax.swing.JMenuBar();
        jmAccueil = new javax.swing.JMenu();
        jmEtablissement = new javax.swing.JMenu();
        jmAjoutEtab = new javax.swing.JMenuItem();
        jmAffichEtab = new javax.swing.JMenuItem();
        jmTChambre = new javax.swing.JMenu();
        jmAjoutChambre = new javax.swing.JMenuItem();
        jmListeChambre = new javax.swing.JMenuItem();
        jmOffres = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmAfficherOffre = new javax.swing.JMenuItem();
        jmAttribution = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmAccueil.setText("Accueil");
        jMenu.add(jmAccueil);

        jmEtablissement.setText("Gestion établissements");
        jmEtablissement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmEtablissementMouseClicked(evt);
            }
        });

        jmAjoutEtab.setText("Créer un établissement");
        jmAjoutEtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAjoutEtabActionPerformed(evt);
            }
        });
        jmEtablissement.add(jmAjoutEtab);

        jmAffichEtab.setText("Afficher établissements");
        jmAffichEtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAffichEtabActionPerformed(evt);
            }
        });
        jmEtablissement.add(jmAffichEtab);

        jMenu.add(jmEtablissement);

        jmTChambre.setText("Gestion types chambres");

        jmAjoutChambre.setText("Créer un type de chambre");
        jmAjoutChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAjoutChambreActionPerformed(evt);
            }
        });
        jmTChambre.add(jmAjoutChambre);

        jmListeChambre.setText("Liste de type de chambre");
        jmListeChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListeChambreActionPerformed(evt);
            }
        });
        jmTChambre.add(jmListeChambre);

        jMenu.add(jmTChambre);

        jmOffres.setText("Offre hébergement");

        jMenuItem1.setText("Créer une offre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmOffres.add(jMenuItem1);

        jmAfficherOffre.setText("Afficher offres");
        jmAfficherOffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAfficherOffreActionPerformed(evt);
            }
        });
        jmOffres.add(jmAfficherOffre);

        jMenu.add(jmOffres);

        jmAttribution.setText("Attribution chambres");

        jMenuItem3.setText("Effectuer une attribution");
        jmAttribution.add(jMenuItem3);

        jMenu.add(jmAttribution);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmEtablissementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmEtablissementMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmEtablissementMouseClicked

    private void jmAjoutEtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAjoutEtabActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jpAjoutEtab);
        pack();
    }//GEN-LAST:event_jmAjoutEtabActionPerformed

    private void jmAjoutChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAjoutChambreActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jfAjoutTChambre);
        pack();
    }//GEN-LAST:event_jmAjoutChambreActionPerformed

    private void jmAffichEtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAffichEtabActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jpConsulterEtab);
        pack();
    }//GEN-LAST:event_jmAffichEtabActionPerformed

    private void jmAfficherOffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAfficherOffreActionPerformed
        this.setContentPane(jpConsulterOffre);
        pack();
    }//GEN-LAST:event_jmAfficherOffreActionPerformed

    private void jmListeChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListeChambreActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jpListeChambre);
        pack();
    }//GEN-LAST:event_jmListeChambreActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setContentPane(jpAjoutOffre);
        pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jfrMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jmAccueil;
    private javax.swing.JMenuItem jmAffichEtab;
    private javax.swing.JMenuItem jmAfficherOffre;
    private javax.swing.JMenuItem jmAjoutChambre;
    private javax.swing.JMenuItem jmAjoutEtab;
    private javax.swing.JMenu jmAttribution;
    private javax.swing.JMenu jmEtablissement;
    private javax.swing.JMenuItem jmListeChambre;
    private javax.swing.JMenu jmOffres;
    private javax.swing.JMenu jmTChambre;
    // End of variables declaration//GEN-END:variables
}
