/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgFestival;

import org.hibernate.Session;
import pkgEntite.HibernateUtil;
import pkgVues.jpAjoutEtab;
import pkgVues.jfAjoutTChambre;
import pkgVues.jpListeChambre;
import pkgEntite.HibernateUtil;


/**
 *
 * @author etudsio
 */
public class jfrMenu extends javax.swing.JFrame {
    private Session session = HibernateUtil.getSessionFactory().openSession();
    /**
     *
     */
    protected jfAjoutTChambre TChambre = new jfAjoutTChambre();
    protected jpAjoutEtab TEtab = new jpAjoutEtab();
    protected jpListeChambre LTChambre = new jpListeChambre();
    protected jpAjoutEtab jpAjoutEtab = new jpAjoutEtab();
    protected jfAjoutTChambre jfAjoutTChambre = new jfAjoutTChambre();

    /**
     * Creates new form jfrMenu
     */
    public jfrMenu() {
        initComponents();
    }    

    public static Session getSession() {
        return session;
    }

    public static void setSession(Session session) {
        this.session = session;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu = new javax.swing.JMenuBar();
        jmAccueil = new javax.swing.JMenu();
        jmEtablissement = new javax.swing.JMenu();
        jmAjoutEtab = new javax.swing.JMenuItem();
        jmTChambre = new javax.swing.JMenu();
<<<<<<< HEAD
        jMenuItem2 = new javax.swing.JMenuItem();
        jmiListeTC = new javax.swing.JMenuItem();
=======
        jmAjoutChambre = new javax.swing.JMenuItem();
>>>>>>> 7c9de83f799e291f901045e52fe9fd3c9884cb08
        jmOffres = new javax.swing.JMenu();
        jmAttribution = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmAccueil.setText("Accueil");
        jMenu.add(jmAccueil);

        jmEtablissement.setText("Gestion établissements");
        jmEtablissement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmEtablissementMouseClicked(evt);
            }
        });

        jmAjoutEtab.setText("Créer un établissement");
        jmAjoutEtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAjoutEtabActionPerformed(evt);
            }
        });
        jmEtablissement.add(jmAjoutEtab);

        jMenu.add(jmEtablissement);

        jmTChambre.setText("Gestion types chambres");
        jmTChambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmTChambreMouseClicked(evt);
            }
        });
        jmTChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTChambreActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        jMenuItem2.setText("Créer un type de chambre");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmTChambre.add(jMenuItem2);
=======
        jmAjoutChambre.setText("Créer un type de chambre");
        jmAjoutChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAjoutChambreActionPerformed(evt);
            }
        });
        jmTChambre.add(jmAjoutChambre);
>>>>>>> 7c9de83f799e291f901045e52fe9fd3c9884cb08

        jmiListeTC.setText("Liste de Type de Chambre");
        jmiListeTC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiListeTCMouseClicked(evt);
            }
        });
        jmiListeTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListeTCActionPerformed(evt);
            }
        });
        jmTChambre.add(jmiListeTC);

        jMenu.add(jmTChambre);

        jmOffres.setText("Offre hébergement");
        jMenu.add(jmOffres);

        jmAttribution.setText("Attribution chambres");

        jMenuItem3.setText("Effectuer une attribution");
        jmAttribution.add(jMenuItem3);

        jMenu.add(jmAttribution);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmEtablissementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmEtablissementMouseClicked
        // TODO add your handling code here:
        this.setContentPane(TEtab);
        pack();
    }//GEN-LAST:event_jmEtablissementMouseClicked

    private void jmTChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTChambreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jmTChambreActionPerformed

    private void jmTChambreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmTChambreMouseClicked
        // TODO add your handling code here:        

    }//GEN-LAST:event_jmTChambreMouseClicked

    private void jmiListeTCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListeTCMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jmiListeTCMouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jmiListeTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListeTCActionPerformed
        // TODO add your handling code here:  
        this.setContentPane(LTChambre);
        pack();
    }//GEN-LAST:event_jmiListeTCActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setContentPane(TChambre);
        pack();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

        
    }                                            

    private void jmAjoutEtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAjoutEtabActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jpAjoutEtab);
        pack();
    }//GEN-LAST:event_jmAjoutEtabActionPerformed

    private void jmAjoutChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAjoutChambreActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jfAjoutTChambre);
        pack();
    }//GEN-LAST:event_jmAjoutChambreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jmAccueil;
    private javax.swing.JMenuItem jmAjoutChambre;
    private javax.swing.JMenuItem jmAjoutEtab;
    private javax.swing.JMenu jmAttribution;
    private javax.swing.JMenu jmEtablissement;
    private javax.swing.JMenu jmOffres;
    private javax.swing.JMenu jmTChambre;
    private javax.swing.JMenuItem jmiListeTC;
    // End of variables declaration//GEN-END:variables
}
