/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVues;

import java.util.Iterator;
import org.hibernate.Query;
import org.hibernate.Session;
import pkgEntite.Etablissement;
import pkgEntite.HibernateUtil;
import pkgFestival.jfrMenu;

/**
 *
 * @author etudsio
 */
public class jpAjoutEtab extends javax.swing.JPanel 
{

    private static Session session = HibernateUtil.getSessionFactory().openSession();
    /**
     * Creates new form jpAjoutEtab
     */
    
    public static Session getSession() {
        return session;
    }

    public static void setSession(Session session) {
        jpAjoutEtab.session = session;
    }
    
    public jpAjoutEtab() {
        initComponents();
        chargerCivilite();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jlTitre = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        txtID = new java.awt.TextField();
        jlNom = new javax.swing.JLabel();
        jlAdresse = new javax.swing.JLabel();
        jlCP = new javax.swing.JLabel();
        jlVille = new javax.swing.JLabel();
        jlTel = new javax.swing.JLabel();
        jlMail = new javax.swing.JLabel();
        jlType = new javax.swing.JLabel();
        txtNom = new java.awt.TextField();
        txtAdresse = new java.awt.TextField();
        txtCP = new java.awt.TextField();
        txtVille = new java.awt.TextField();
        txtTel = new java.awt.TextField();
        txtMail = new java.awt.TextField();
        btnType = new javax.swing.JRadioButton();
        btnType2 = new javax.swing.JRadioButton();
        jlResponsable = new javax.swing.JLabel();
        jlCiviliteResp = new javax.swing.JLabel();
        lstCiviliteResp = new javax.swing.JComboBox();
        jlNomResp = new javax.swing.JLabel();
        jlPrenomResp = new javax.swing.JLabel();
        txtNomResp = new java.awt.TextField();
        txtPrenomResp = new java.awt.TextField();
        btnValider = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        jlTitre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlTitre.setText("Nouvel Etablissement");

        jlID.setText("ID * :");

        jlNom.setText("Nom* :");

        jlAdresse.setText("Adresse* :");

        jlCP.setText("Code Postal* :");

        jlVille.setText("Ville* :");

        jlTel.setText("Téléphone* :");

        jlMail.setText("Mail :");

        jlType.setText("Type* :");

        btnType.setText("Etablissement Scolaire");

        btnType2.setText("Autre");

        jlResponsable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlResponsable.setText("Responsable");

        jlCiviliteResp.setText("Civilité* :");

        lstCiviliteResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstCiviliteRespActionPerformed(evt);
            }
        });

        jlNomResp.setText("Nom* :");

        jlPrenomResp.setText("Prénom* :");

        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitre)
                .addGap(276, 276, 276))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlType)
                        .addGap(246, 618, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlNom)
                                .addGap(46, 46, 46)
                                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlAdresse)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlCP, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jlVille))
                                    .addComponent(jlTel)
                                    .addComponent(jlMail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnType)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnType2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtVille, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(2, 2, 2))
                                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 372, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCiviliteResp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lstCiviliteResp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnValider)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnAnnuler)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlNomResp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomResp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                        .addComponent(jlPrenomResp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrenomResp, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlResponsable)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlID)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTitre)
                        .addGap(48, 48, 48)
                        .addComponent(jlID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAdresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlVille))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnType)
                    .addComponent(jlType)
                    .addComponent(btnType2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlResponsable)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCiviliteResp)
                            .addComponent(lstCiviliteResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNomResp)))
                    .addComponent(txtNomResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPrenomResp)
                    .addComponent(txtPrenomResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValider)
                    .addComponent(btnAnnuler))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        // TODO add your handling code here:
        Etablissement unNewEtablissement = new Etablissement();
        unNewEtablissement.setEtaNom(txtNom.getText());
        unNewEtablissement.setEtaRue(txtAdresse.getText());
        unNewEtablissement.setEtaCp(txtCP.getText());
        unNewEtablissement.setEtaVille(txtVille.getText());
        unNewEtablissement.setEtaTel(txtTel.getText());
        unNewEtablissement.setEtaMail(txtMail.getText());
        unNewEtablissement.setEtaType(btnType.getText());
        unNewEtablissement.setEtaCivilresp(lstCiviliteResp);
        unNewEtablissement.setEtaNomresp(txtNomResp.getText());
        unNewEtablissement.setEtaPrenomresp(txtPrenomResp.getText());
    }//GEN-LAST:event_btnValiderActionPerformed

    private void lstCiviliteRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstCiviliteRespActionPerformed
        // TODO add your handling code here:
              
    }//GEN-LAST:event_lstCiviliteRespActionPerformed
    private void chargerCivilite()
    {
            String sReq = "from Etablissement";
            jfrMenu.getSession().beginTransaction();
            Query q = jfrMenu.getSession().createQuery(sReq);

            Iterator civilite = q.iterate();
//            while (civilite.hasNext()){
//                Etablissement uneCivilite = (Etablissement)civilite.next();
//                lstCiviliteResp.addItem(uneCivilite.getEtaCivilresp());
//            }
                lstCiviliteResp.addItem("Monsieur");
                lstCiviliteResp.addItem("Madame");
            //bCharge = true;
     } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JRadioButton btnType;
    private javax.swing.JRadioButton btnType2;
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlAdresse;
    private javax.swing.JLabel jlCP;
    private javax.swing.JLabel jlCiviliteResp;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlMail;
    private javax.swing.JLabel jlNom;
    private javax.swing.JLabel jlNomResp;
    private javax.swing.JLabel jlPrenomResp;
    private javax.swing.JLabel jlResponsable;
    private javax.swing.JLabel jlTel;
    private javax.swing.JLabel jlTitre;
    private javax.swing.JLabel jlType;
    private javax.swing.JLabel jlVille;
    private javax.swing.JComboBox lstCiviliteResp;
    private java.awt.TextField txtAdresse;
    private java.awt.TextField txtCP;
    private java.awt.TextField txtID;
    private java.awt.TextField txtMail;
    private java.awt.TextField txtNom;
    private java.awt.TextField txtNomResp;
    private java.awt.TextField txtPrenomResp;
    private java.awt.TextField txtTel;
    private java.awt.TextField txtVille;
    // End of variables declaration//GEN-END:variables
}
