/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVues;

import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import pkgEntite.Etablissement;
import pkgFestival.jfrMenu;

/**
 *
 * @author etudsio
 */
public class jpConsulterEtab extends javax.swing.JPanel {

    /**
     * Creates new form jpConsulterEtab
     */
    public jpConsulterEtab() {
        initComponents();
        chargerTable();
    }

    public void chargerTable() {
        //On charge la liste des établissements dans un tableau
        int nbligne;
        int i;
        nbligne = TabEtab.getRowCount();
        if(nbligne > 0){
            for(i=0; i < nbligne; i++){
                ((DefaultTableModel)TabEtab.getModel()).removeRow(0);
            }
        String sReq = "From Etablissement";
        
        Query q = jfrMenu.getSession().createQuery(sReq);
        Iterator etab = q.iterate();
        while(etab.hasNext()){
            Etablissement unEtablissement = (Etablissement) etab.next();
            ((DefaultTableModel) TabEtab.getModel()).addRow(newObject[] (unEtablissement.getEtaId(), unEtablissement.getEtaNom()));
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabEtab = new javax.swing.JTable();

        TabEtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Etablissement"
            }
        ));
        jScrollPane1.setViewportView(TabEtab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(138, 138, 138))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabEtab;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
